language: ruby
cache: bundler
rvm:
  - 2.5.1
addons:
  ssh_known_hosts:
    - www.clir.org
before_install:
  - openssl aes-256-cbc -K $encrypted_2384c7572be8_key -iv $encrypted_2384c7572be8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - gem update --system
before_script:
  - chmod +x ./script/cibuild
script: "./script/cibuild"
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git remote add deploy $git_remote
  - git push deploy master
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
