language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - gem update --system
before_script:
  - chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
