language: ruby
cache: bundler
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_2384c7572be8_key -iv $encrypted_2384c7572be8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- gem update --system
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
