# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DLF Dashboard
email: info@diglib.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dashboard" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  style: compressed

# For https://github.com/jekyll/jekyll-seo-tag
author:
logo:

social:
  name: Digital Library Federation
  links:
    - https://twitter.com/clirdlf
    - https://www.facebook.com/CLIRDLF/
    - https://www.linkedin.com/groups/3387265
    - https://www.youtube.com/user/DLFCLIR
    - https://github.com/clirdlf

twitter:
  username: clirdlf

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

# https://github.com/jekyll/jekyll-feed
feed:
  path: atom.xml

kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ...}

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - gulpfile.js
  - package*.json
  - node_modules
  - js/build
  - js/src
  - script
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
